spring:
  datasource:
    username: root
    password: zero
    url: jdbc:mysql://localhost:3306/blog
  jpa:
    hibernate:
      ddl-auto: update
  security:
    user:
      name: hemant
      password: hemant
